### ISSUE TITLE
[jpackage] Issue with upgrading from javapackager to jpackage on Windows

### ISSUE THREAD

**Issue by danielpeintner** [danielpeintner/Java11Test#2]
As described in the [core-libs-dev](https://mail.openjdk.java.net/pipermail/core-libs-dev/2020-February/064812.html) list we are experiencing issues replacing the *old* javapackager InnoSetup with the *new* jpackage MSI installer.

Updating seems to work first but the installation is broken when upgrading. The only *working* solution we found was to *manually* uninstall the old application before starting msi installer (we are not WiX experts though).

@brunchboy mentioned that @Kevinnns was able to find a solution for [beat-link-trigger](https://github.com/Deep-Symmetry/beat-link-trigger/commits?author=Kevinnns).

@Kevinnns may I ask you whether you can provide a working path for people having the same problem. I think it would be good if we can share it on core-libs-dev again.

jpackage provides a related option but I did not succeed using it.
`--win-upgrade-uuid <string> — UUID associated with upgrades for this package`

Thanks!

**Comment by Kevinnns** [comment]
I don't see myself as an expert in WIX as well if I'm honest, I just got it working.

What I saw in the WIX template jpackage uses, the Upgrade code has been set in the <PRODUCT> component of the template like this (could be a bit different in the jpackage template though): 

` <Product Id="*" Name="$(var.AppName)" Language="1033" Version="$(var.AppVersion)" Manufacturer="$(var.AppVendor)" UpgradeCode="$(var.AppUpgradeCode)"> `

But to let upgrades succeed, you'll need to add `<Upgrade Id="$(var.AppUpgradeCode)" />` as well within the product piece. At least, that is what I've noticed in the past and has worked for BLT.

Pending on how jpackage passes on such defined variables to WIX, it could be as easy as just adding that `<Upgrade Id="$(var.AppUpgradeCode)" />` within the PRODUCT piece fairly at the top, if the variable is defined off course. Also take a look at MajorUpgrade part of the Template.

Here is a link for the one that is working for us. https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/.github/resources/MSI%20Template.wxs

Mind you, for BLT we don't use jpackage at this point anymore. To create an up-gradable MSI, we only let it create an .exe application for windows, at a later point we scripted it to being put into a MSI using WIX.

https://github.com/Deep-Symmetry/beat-link-trigger/blob/master/.github/scripts/build_msi.ps1

Does all this info help you @danielpeintner ?

**Comment by danielpeintner** [comment]
Thanks for the feedback.

I will also ask again the jpackage team whether such a change is accepted.

**Comment by danielpeintner** [comment]
https://bugs.openjdk.java.net/browse/JDK-8240111

**Comment by danielpeintner** [comment]
Installation works but launching app fails 
https://github.com/openjdk/jdk/pull/940/ related ?

**Comment by danielpeintner** [comment]
Resolved by creating batch script that uninstalls first old installer and uses afterward the *new* MSI installer.
